# Dedicated styling for menus launched through dmenu_command.
dpi-aware=no
width=60
; font=sf mono:bold:size=18
font=Ttyp0 OTB:bold:size=18,Apple Color Emoji:size=16
line-height=40
prompt="❯   "
exit-on-keyboard-focus-loss=no

[border]
radius=8
width=0

[colors]
background="#1a1a1aff"
text="#ebdbb2ff"
selection="#005577ff"
selection-text="#ebdbb2ff"
match="#83a598ff"
selection-match="#d3869bff"
border="#005577ff"

[dmenu]
exit-immediately-if-empty=yes
