#!/bin/bash
os=`lsb_release -r | sed 's/.*://'`
echo $os
if [ $os="16.04" ]
then
    echo "opencv libs for 16.04 is being installed !"
    sudo apt-get install -y  build-essential checkinstall cmake pkg-config yasm \
    git \
    gfortran \
    libjpeg8-dev libjasper-dev libpng12-dev \
    libtiff5-dev \
    libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev \
    libxine2-dev libv4l-dev \
    libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev \
    qt5-default libgtk2.0-dev libtbb-dev \
    libatlas-base-dev \
    libfaac-dev libmp3lame-dev libtheora-dev \
    libvorbis-dev libxvidcore-dev \
    libopencore-amrnb-dev libopencore-amrwb-dev \
    x264 v4l-utils \
    libprotobuf-dev protobuf-compiler \
    libgoogle-glog-dev libgflags-dev \
    libgphoto2-dev libeigen3-dev libhdf5-dev doxygen \
elif [ $os="18.04" ]
    echo "opencv libs for 18.04 is being installed !"
    sudo apt-get install libopencv-dev 
else
    echo "didn't install opencv libs"
fi
