#
# ~/.bash_profile
#
export VISUAL="/usr/bin/vim" # for crontab -e
export EDITOR=nvim 
export TERMINAL=alacritty
export BROWSER=brave
export LD_LIBRARY_PATH="/usr/local/lib"
export LIBVA_DRIVER_NAME=iHD

PATH=$PATH:$HOME/.scripts/tools
PATH=$PATH:$HOME/.scripts/commands
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.local/bin/helpers
PATH=$PATH:$HOME/.local/bin/scripts
PATH=$PATH:$HOME/.local/bin/scripts/tools
PATH=$PATH:$HOME/.local/bin/scripts/commands
PATH=$PATH:$HOME/.local/bin/screenlayout
PATH=$PATH:$HOME/.local/bin/statusbar
PATH=$PATH:$HOME/go/bin
PATH=$PATH:/var/lib/snapd/snap/bin
PATH=$PATH:/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/

# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"
