#!/bin/sh

[ -f `which undervolt.sh` ] && undervolt.sh
# Enable basic sound output via pulseaudio
# Run "pacmd list-sinks | grep -e 'name:' -e 'index'" to find your QEMU_PA_SINK
export QEMU_AUDIO_DRV=pa
export QEMU_PA_SINK=alsa_output.pci-alsa_output.pci-0000_00_1f.3.analog-stereo.analog-stereo
export QEMU_PA_SOURCE=input
# * index: 0
#         name: <alsa_output.pci-0000_00_1f.3.analog-stereo>

# Start QEMU
qemu-system-x86_64 \
    -enable-kvm \
    -m 2G \
    -smp cores=2,threads=2,sockets=1,maxcpus=4 \
    -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
    -machine type=pc,accel=kvm,kernel_irqchip=on \
    -global PIIX4_PM.disable_s3=1 \
    -global PIIX4_PM.disable_s4=1 \
    -name windows-gvt-g-guest \
    -usb \
    -device usb-tablet \
    -display gtk,gl=on \
    -device vfio-pci,sysfsdev=/sys/devices/pci0000:00/0000:00:02.0/62b5e1eb-1193-4ea8-9e22-5df5a5bc366a,x-igd-opregion=on,display=on \
    -drive file=/home/vm/qemu/windows_10.qcow2,format=qcow2,l2-cache-size=8M \
    -cdrom /home/rafael/iso/en_windows_10_pro_rs4_version_1803_17134_191_updated_july_2018_x64_dvd.iso \
    -netdev user, id=net0, hostfwd=tcp::2222-:22
    # -net nic -net user,restrict=on,smb=/home/rafael


    # -vga qxl \
    # -nic tap

    # -nic user,model=virtio-net-pci
    # -soundhw hda \

# https://www.youtube.com/watch?v=7RNvGM7Wkhs
# qemu-system-x86_64 \
#     -enable-kvm \
#     -m 16G \
#     -smp cores=4,threads=1,sockets=1,maxcpus=4 \
#     -machine type=q35 \
#     -cpu host \
#     -name Win10 \
#     -soundhw hda \
#     -usb \
#     -display gtk,gl=on \
#     -device usb-tablet \
#     -device vfio-pci,sysfsdev=/sys/devices/pci0000:00/0000:00:02.0/GPU ID,x-igd-opregion=on,display=on \
#     -drive file=windows.qcow2,format=qcow2 \
#     -vga none \
#     -net nic \
#     -net user
