#!/usr/bin/env sh

while read file
do
    case "$1" in
        "w") wal -n -i "$file" --backend `wal --backend | awk '{print $2}' | awk '/[a-z]/' | dmenu -i -p "choose pywal backend" -l 15` || sleep 3 && xrdb ~/.cache/wal/.Xresources && setbg "$file" || notify-send "wallpaper failed";;
        # "e") $TERMINAL -e vim ~/.config/sxiv/exec/key-handler & ;;
        "e") $TERMINAL -e vim  ~/.config/sxiv/exec/key-handler & ;;
        "o") pkill sxiv && sxiv -t `dirname "$file"` || notify-send "$file" ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
            ;;
        "m")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
            ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "y")
            echo -n "$file" | xclip -selection clipboard &&
                notify-send "$file copied to clipboard" & ;;
        "Y")
            readlink -f "$file" | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "g")	ifinstalled gimp && gimp "$file" & ;;
            esac
done
