#!/usr/bin/env sh

while read -r file
do
    case "$1" in
        "w")
            pkill swaybg
            cp "$file" ~/.config/wall-tile.png
            swaybg -m tile -i "$file" &
            exit ;;
        "W") pkill swaybg ; rm ~/.config/wall.png ; rm ~/.config/wall-tile.png ; cp "$file" ~/.config/wall.png ; swaybg -i "$file" & ;;
        "q") apply-hald-clut.sh "$file" | xargs -L 1 notify-send ;;
        "l") $TERMINAL -e vim ~/.local/bin/apply-hald-clut.sh "$file" ;;
        "j") convert $file ${file}.jpg ;;
        # "e") $TERMINAL -e vim ~/.config/sxiv/exec/key-handler & ;;
        "e") $TERMINAL -e vim  ~/.config/sxiv/exec/key-handler & ;;
        "o") pkill sxiv && sxiv -t `dirname "$file"` || notify-send "$file" ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu_command --lines=20 --prompt="Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
            ;;
        "m")
            [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/directories | awk '{print $2}' | dmenu_command --lines=20 --prompt="Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ -z "$destdir" ] && exit
            mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
            ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop -flip "$file" "$file" ;;
        "y")
            cat "$file" | wl-copy --type image/png &&
                notify-send "$file copied to clipboard" & ;;
        "Y")
            readlink -f "$file" | wl-copy &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu_command --prompt="Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "g")	gimp && gimp "$file" & ;;
            esac
done
