#!/bin/sh
choices="lock\nsuspend\nshutdown\nlogout"

chosen=$(echo -e "$choices" | dmenu -i -p "Choose what to do ?" -l 15)
case "$chosen" in
    lock) betterlockscreen --lock blur -r 1280x720;;
    suspend) betterlockscreen -s --lock blur;;
    shutdown) ~/.scripts/tools/prompt "Do you want to shutdown ?" "shutdown now";;
    logout) i3-msg exit;;
esac
