#!/bin/sh

# load colors from wal
[[ -f $HOME/.cache/wal/colors.sh ]] && source "$HOME/.cache/wal/colors.sh"

alias ka="killall" \
	mkd="mkdir -pv" \
	calcurse="calcurse -D ~/.config/calcurse" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yta="yt -x -f bestaudio/best --audio-format mp3" \
    yt_playlist="youtube-dl -f 136+250 -citk –format mp4 –yes-playlist -c" \
    yt_best="youtube-dl -f 248+250" \
    yt_480="youtube-dl -f 135+250" \
    yt_720="youtube-dl -f 136+250" \
	ffmpeg="ffmpeg -hide_banner" \
    ta='tmux attach -t' \
    tad='tmux attach -d -t' \
    ts='tmux new-session -s' \
    tl='tmux list-sessions' \
    tksv='tmux kill-server' \
    tkss='tmux kill-session -t' \
    red='redshift -O' \
    ured='redshift -x' \
    la='ls -a' \
    battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0' \
    doc='$BROWSER /usr/share/doc/arch-wiki/html/en > /dev/null' \
    minecraft='java -jar ~/software/TLauncher-2.67/TLauncher-2.67.jar' \
    do='vim ~/Dropbox/todo.md' \
    corona='curl https://corona-stats.online' \
    weather='curl https://wttr.in/stepanakert' \
    doc_ardupilot='chromium ~/github/adana/docs/docs/parameters.html' \
    dict='"sdcv' \
    books='ranger $HOME/Dropbox/books' \
    nd='nordvpn disconnect' \
    nc='nordvpn connect romania' \
    tn='tmux new -s' \
    cp='cp -iv' \
    inav='~/software/inav/INAV\ Configurator/inav-configurator' \
	# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \


pgrep -x dmenu && exit
export EDITOR=vim 
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

PATH=$PATH:$HOME/.scripts/tools
PATH=$PATH:$HOME/.scripts/commands
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.local/bin/scripts
PATH=$PATH:$HOME/.local/bin/screenlayout
PATH=$PATH:$HOME/.gem/ruby/2.6.0/bin
export PATH

vf() { fzf | xargs -r -I % $EDITOR % ;}
