#!/bin/sh

# load colors from wal
[[ -f $HOME/.cache/wal/colors.sh ]] && source "$HOME/.cache/wal/colors.sh"

alias ka="killall" \
    vi='/usr/bin/vim' \
    rm='trash' \
    x="sxiv -ft *" \
    cam='ranger ~/phone/Camera/' \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    yta="youtube-dl -x -f bestaudio/best --audio-format mp3" \
    yt_playlist="youtube-dl -f 140+137 -citk –format mp4 –yes-playlist -c" \
    yt_best="youtube-dl -f 248+250" \
    yt_480="youtube-dl -f 135+250" \
    yt_720="youtube-dl -f 136+250" \
    ffmpeg="ffmpeg -hide_banner" \
    red='redshift -O' \
    ured='redshift -x' \
    battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0' \
    doc='$BROWSER /usr/share/doc/arch-wiki/html/en > /dev/null' \
    minecraft='java -jar ~/software/TLauncher-2.67/TLauncher-2.67.jar' \
    d='todo.sh' \
    weather='curl https://wttr.in/stepanakert' \
    dict='sdcv' \
    cp='cp -iv' \
    inav='~/software/inav/INAV\ Configurator/inav-configurator' \
    wallpaper='sxiv ~/Dropbox/wallpaper' \
    bton='bluetoothctl power on' \
    btoff='bluetoothctl power off' \
    paru='paru --bottomup' \
    study='mpv ~/Videos/study.mp4' \
    tree='exa --tree --level=2 --long -a --header --git' \
    sl='ls' \
    noise='mpv ~/Music/white_noise.mp3' \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

PATH=$PATH:$HOME/.scripts/tools
PATH=$PATH:$HOME/.scripts/commands
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.local/bin/utils
PATH=$PATH:$HOME/.local/bin/scripts
PATH=$PATH:$HOME/.local/bin/scripts/tools
PATH=$PATH:$HOME/.local/bin/scripts/commands
PATH=$PATH:$HOME/.local/bin/screenlayout
PATH=$PATH:$HOME/.local/bin/statusbar
PATH=$PATH:/opt/gcc-arm-none-eabi-9-2020-q2-update/bin
vf() { fzf | xargs -r -I % $EDITOR % ;}
