#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
    yt_playlist="youtube-dl -f 136+250 -citk –format mp4 –yes-playlist -c" \
    yt_best="youtube-dl -f 248+250" \
    yt_480="youtube-dl -f 135+250" \
    yt_720="youtube-dl -f 136+250" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
    ta='tmux attach -t' \
    tad='tmux attach -d -t' \
    ts='tmux new-session -s' \
    tl='tmux list-sessions' \
    tksv='tmux kill-server' \
    tkss='tmux kill-session -t' \
    red='redshift -O' \
    ured='redshift -x' \
    la='ls -a' \
    battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0'

pgrep -x dmenu && exit
export EDITOR=vim 
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

PATH=$PATH:$HOME/.scripts/tools
PATH=$PATH:$HOME/.gem/ruby/2.6.0/bin
export PATH

vf() { fzf | xargs -r -I % $EDITOR % ;}
